apiVersion: v1
kind: Pod
metadata:
  name: cdm-debug
  namespace: hcd-epk60j1n
  labels:
    app: cdm-migration
    component: debug
spec:
  containers:
  - name: debug
    image: ubuntu:22.04
    command: 
      - sleep
      - "3600"
    volumeMounts:
    - name: cdm-data
      mountPath: /data
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  volumes:
  - name: cdm-data
    persistentVolumeClaim:
      claimName: cdm-data-pvc
  restartPolicy: Never