# This isn't part of normal cass-operator deployment, only for mission-control
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-cass-operator-metrics
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    control-plane: {{ include "k8ssandra-common.fullname" . }}-cass-operator-controller-manager
    app.kubernetes.io/name: cass-operator
