apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "k8ssandra-common.fullname" . }}-manager-role
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - secrets/finalizer
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - batch
  resources:
    - cronjobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cassandra.datastax.com
  resources:
    - cassandradatacenters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cert-manager.io
  resources:
    - certificates
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - cert-manager.io
  resources:
    - issuers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - config.k8ssandra.io
  resources:
    - clientconfigs
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - control.k8ssandra.io
  resources:
    - cassandratasks
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - control.k8ssandra.io
  resources:
    - k8ssandratasks
  verbs:
    - create
    - list
- apiGroups:
    - ""
  resources:
    - configmaps
    - namespaces
    - secrets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - endpoints
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8ssandra.io
  resources:
    - k8ssandraclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - k8ssandra.io
  resources:
    - k8ssandraclusters/finalizers
  verbs:
    - update
- apiGroups:
    - k8ssandra.io
  resources:
    - k8ssandraclusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusabackupjobs
  verbs:
    - create
    - get
    - list
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusabackups
  verbs:
    - get
    - list
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusabackupschedules
  verbs:
    - create
    - delete
    - get
    - list
    - patch
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusaconfigurations
  verbs:
    - create
    - delete
    - get
    - list
    - patch
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusarestorejobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
- apiGroups:
    - medusa.k8ssandra.io
  resources:
    - medusatasks
  verbs:
    - create
    - delete
    - get
    - list
    - patch
- apiGroups:
    - missioncontrol.datastax.com
  resources:
    - missioncontrolclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - missioncontrol.datastax.com
  resources:
    - missioncontrolclusters/finalizers
  verbs:
    - update
- apiGroups:
    - missioncontrol.datastax.com
  resources:
    - missioncontrolclusters/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - networking.k8s.io
  resources:
    - networkpolicies
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - reaper.k8ssandra.io
  resources:
    - reapers
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - replication.k8ssandra.io
  resources:
    - replicatedsecrets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - security.openshift.io
  resourceNames:
    - anyuid
  resources:
    - securitycontextconstraints
  verbs:
    - use
- apiGroups:
    - stargate.k8ssandra.io
  resources:
    - stargates
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - get
    - list
