{{- $certmanager := .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
{{- $disableCertManagerCheck := .Values.disableCertManagerCheck -}}

{{- if not $certmanager -}}
  {{- if not $disableCertManagerCheck -}}
    {{- fail (print "mission-control webhooks require cert-manager to be installed in the cluster") }}
  {{- end -}}
{{- end -}}

kind: ConfigMap
metadata:
  name: {{ include "k8ssandra-common.fullname" . }}-manager-config
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: f5feed0c.datastax.com
