# The conversion webhook for MissionControlClusters is configured in the CRD itself (see ../../crds).
# Helm does not allow templating in CRDs, yet some aspects of that configuration are dynamic.
# This job patches the CRD after its deployment to set the correct values.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "k8ssandra-common.fullname" . }}-crd-patcher
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    # This must run after the crd-upgrader job
    "helm.sh/hook-weight": "20"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels: {{ include "k8ssandra-common.labels" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ template "k8ssandra-common.fullname" . }}-crd-upgrader
      containers:
      - name: kubectl
        image: {{ include "k8ssandra-common.flattenedImage" .Values.crdPatchJob.image }}
        imagePullPolicy: {{ .Values.crdPatchJob.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.crdPatchJob.securityContext | nindent 10 }}
        args:
        - patch
        - crd
        - missioncontrolclusters.missioncontrol.datastax.com
        - --type
        - json
        - -p
        - |
          [
            {
              "op": "replace",
              "path": "/metadata/annotations/cert-manager.io~1inject-ca-from",
              "value": "{{ .Release.Namespace }}/{{ include "k8ssandra-common.fullname" . }}-serving-cert"
            },
            {
              "op": "replace",
              "path": "/spec/conversion/webhook/clientConfig/service/namespace",
              "value": "{{ .Release.Namespace }}"
            }
          ]
      {{- if .Values.crdPatchJob.image.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.crdPatchJob.image.imagePullSecret }}
      {{- end }}
