{
 "title": "Cassandra Overview",
 "tags": [
  "Cassandra",
  "Overview"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "Prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_compaction_completed_tasks{}, cluster)"
    }
   },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\"}, datacenter)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\"}, rack)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\"}, pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Throughputs (Coordinator Perspective)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Throughputs",
   "type": "timeseries",
   "description": "Total Requests Per Cluster, by Request Type",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Cassandra {{request_type}}"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(stargate_client_request_latency_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Stargate {{request_type}}"
    }
   ]
  },
  {
   "title": "Error throughputs",
   "type": "timeseries",
   "description": "Total Timeouts, Failures, Unavailable Rates for each cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_failures_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} failures"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_timeouts_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} timeouts"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_unavailables_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} unavailable errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_unfinished_commit{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} unfinished commit errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_condition_not_met{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} condition not met errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(org_apache_cassandra_metrics_client_request_contention_histogram_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{request_type}} contention histogram errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(stargate_client_request_failures_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Stargate {{request_type}} failures"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(stargate_client_request_timeouts_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Stargate {{request_type}} timeouts"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(stargate_client_request_unavailables_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Stargate {{request_type}} unavailable errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(stargate_client_request_unfinished_commit_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Stargate {{request_type}} unfinished commit errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(stargate_client_request_condition_not_met_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Stargate {{request_type}} condition not met errors"
    },
    {
     "expr": "sum by (cluster, request_type) (rate(stargate_client_request_contention_histogram_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "Stargate {{request_type}} contention histogram errors"
    }
   ]
  },
  {
   "title": "Read / Write Distribution",
   "type": "gauge",
   "description": "Part of reads in the total of standard requests (Reads+Writes). CAS, Views, ... operations are ignored.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( sum by (cluster) (rate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s]))  ) / (sum by (cluster) (rate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s])) + sum by (cluster) (rate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Write\"}[1m:30s])))"
    }
   ]
  },
  {
   "title": "Read Latency (98 - 999th percentile)",
   "type": "timeseries",
   "description": "Read latency for coordinated reads",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Read\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p999"
    },
    {
     "expr": "stargate_client_request_latency_quantile{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", quantile=~\"0.98\", request_type=\"read\"}*1000000",
     "legendFormat": "Stargate p98"
    },
    {
     "expr": "stargate_client_request_latency_quantile{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", quantile=~\"0.99\", request_type=\"read\"}*1000000",
     "legendFormat": "Stargate p99"
    },
    {
     "expr": "stargate_client_request_latency_quantile{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", quantile=~\"0.999\", request_type=\"read\"}*1000000",
     "legendFormat": "Stargate p999"
    }
   ]
  },
  {
   "title": "Write Latency (98th - p999 Percentile)",
   "type": "timeseries",
   "description": "Write latency for coordinated writes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Write\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Write\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type=\"Write\"}[1m:30s])) by (le, cluster))",
     "legendFormat": "p999"
    },
    {
     "expr": "stargate_client_request_latency_quantile{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", quantile=~\"0.98\", request_type=\"write\"}*1000000",
     "legendFormat": "Stargate p98"
    },
    {
     "expr": "stargate_client_request_latency_quantile{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", quantile=~\"0.99\", request_type=\"write\"}*1000000",
     "legendFormat": "Stargate p99"
    },
    {
     "expr": "stargate_client_request_latency_quantile{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", quantile=~\"0.999\", request_type=\"write\"}*1000000",
     "legendFormat": "Stargate p999"
    }
   ]
  },
  {
   "title": "Other Latencies",
   "type": "timeseries",
   "description": "Other p99 latencies for coordinated requests",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", request_type!~\"Write|Read|.*-.*\"}[1m:30s])) by (le, request_type, cluster))",
     "legendFormat": "p99 {{request_type}}"
    },
    {
     "expr": "stargate_client_request_latency_quantile{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", quantile=~\"0.99\", request_type!~\"write|read|.*-.*\"}*1000000",
     "legendFormat": "Stargate p99 {{request_type}}"
    }
   ]
  },
  {
   "title": "Nodes Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Status",
   "type": "grafana-polystat-panel",
   "description": "Nodes Status uses Internal/Gossip activity. Be mindful that if Native or Thrift protocol are disabled, the nodes won't be reachable, and still marked up",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max by (cluster, dc, rack, pod_name) (changes(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\", pool_name=\"GossipStage\", pool_type=\"internal\"}[1m:30s])) > bool 0",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Nodes Count",
   "type": "stat",
   "description": "Nodes up and down in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (cluster) (max by (cluster, dc, rack, instance) (org_apache_cassandra_metrics_compaction_completed_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}))",
     "legendFormat": "Total Number Of Nodes"
    }
   ]
  },
  {
   "title": "Nodes Status History",
   "type": "timeseries",
   "description": "Nodes up and down in the cluster per protocol/activity",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (cluster) (max by (cluster, dc, rack, instance) (org_apache_cassandra_metrics_compaction_completed_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}))",
     "legendFormat": "Total Number Of Nodes"
    }
   ]
  },
  {
   "title": "Data Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "description": "Disk space used ordered (fullest disks first)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(host, device) (host_filesystem_used_ratio{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "{{host}} - {{device}}"
    }
   ]
  },
  {
   "title": "Cassandra cluster Data Size",
   "type": "graph",
   "description": "Total sizes of the data on distinct nodes",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_table_live_disk_space_used{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Live space - {{cluster}}"
    },
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_table_total_disk_space_used{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Total space - {{cluster}}"
    }
   ]
  },
  {
   "title": "SSTable Count",
   "type": "graph",
   "description": "SSTable Count Max and Average per table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (cluster, keyspace, table) (org_apache_cassandra_metrics_table_live_ss_table_count{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Table - {{keyspace}}.{{table}}"
    },
    {
     "expr": "max by (cluster) (org_apache_cassandra_metrics_table_live_ss_table_count{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Max in cluster - {{cluster}}"
    }
   ]
  },
  {
   "title": "Pending Compactions",
   "type": "graph",
   "description": "Maximum pending compactions on any node in the cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Pending Compactions per Table",
   "type": "graph",
   "description": "Maximum pending compactions per table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (cluster, keyspace, table) (org_apache_cassandra_metrics_table_pending_compactions{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "max for {{keyspace}}.{{table}}"
    }
   ]
  },
  {
   "title": "Cassandra Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "graph",
   "description": "Cluster wide pending threads, by thread pool name",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (org_apache_cassandra_metrics_thread_pools_pending_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "{{cluster}} - pending {{pool_name}}"
    }
   ]
  },
  {
   "title": "Blocked Tasks",
   "type": "graph",
   "description": "Cluster wide blocked threads, by thread pool name",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (rate(org_apache_cassandra_metrics_thread_pools_total_blocked_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{cluster}} - blocked {{pool_name}}"
    }
   ]
  },
  {
   "title": "Dropped Messages",
   "type": "graph",
   "description": "Dropped messages rate summed by message type and cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, message_type) (rate(org_apache_cassandra_metrics_dropped_message_dropped_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "{{cluster}} - dropped {{message_type}}"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "graph",
   "description": "active threads summed per cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster, pool_name) (org_apache_cassandra_metrics_thread_pools_active_tasks{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "{{cluster}} - active {{pool_name}}"
    }
   ]
  },
  {
   "title": "Hinted Handoff",
   "type": "graph",
   "description": "Sum of hints being handed off per cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (org_apache_cassandra_metrics_storage_total_hints_in_progress{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Hardware / Operating System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Maximum CPU utilisation (max 100%)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (cluster) (1 - (sum by (host) (rate(host_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / sum by (host) (rate(host_cpu_seconds_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))))",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "min by (cluster) (1 - (sum by (host) (rate(host_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / sum by (host) (rate(host_cpu_seconds_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))))",
     "legendFormat": "min {{host}}"
    },
    {
     "expr": "avg by (cluster) (1 - (sum by (host) (rate(host_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / sum by (host) (rate(host_cpu_seconds_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))))",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Unix Load (1m rate)",
   "type": "timeseries",
   "description": "Max Unix load on a node for a cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (cluster) (host_load1{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (host_load1{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (host_load1{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "timeseries",
   "description": "Maximum Memory allocated per usage (worst node) - excludes caches, buffers, etc",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (cluster) (host_memory_used_bytes{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "min by (cluster) (host_memory_used_bytes{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "min {{host}}"
    },
    {
     "expr": "avg by (cluster) (host_memory_used_bytes{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Disk Read Thoughput",
   "type": "timeseries",
   "description": "Disk read throughput",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (cluster) (rate(host_disk_read_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "min by (cluster) (rate(host_disk_read_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "min {{host}}"
    },
    {
     "expr": "avg by (cluster) (rate(host_disk_read_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Disk Write Thoughput",
   "type": "timeseries",
   "description": "Disk write throughput",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (cluster) (rate(host_disk_written_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "min by (cluster) (rate(host_disk_written_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]))",
     "legendFormat": "min {{host}}"
    },
    {
     "expr": "avg by (cluster) (rate(host_disk_written_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "avg {{host}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Network In and Out per cluster",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(host_network_transmit_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "outgoing"
    },
    {
     "expr": "sum by (cluster) (rate(host_network_receive_bytes_total{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "incoming"
    }
   ]
  },
  {
   "title": "JVM / Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Application Throughput (% time NOT doing GC)",
   "type": "timeseries",
   "description": "Percentage of the time the node is *not* doing a GC, thus Cassandra is not stopped for GC",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (cluster) (1 - (sum by (cluster, dc, rack, instance) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]) + rate(jvm_gc_g1_old_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / 1000))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (1 - (sum by (cluster, dc, rack, instance) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]) + rate(jvm_gc_g1_old_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / 1000))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (1 - (sum by (cluster, dc, rack, instance) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s]) + rate(jvm_gc_g1_old_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"}[1m:30s])) / 1000))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Garbage Collection Time",
   "type": "graph",
   "description": "Garbage collection duration",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (cluster) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "max"
    },
    {
     "expr": "min by (cluster) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster) (rate(jvm_gc_g1_young_generation_time{cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"}[1m:30s]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "JVM Memory Utilisation",
   "type": "timeseries",
   "description": "Maximum JVM Heap Memory size (worst node) and minimum available heap size",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(jvm_memory_bytes_used) by(area)",
     "legendFormat": "max {{area}}"
    },
    {
     "expr": "min by (cluster)\n        (jvm_memory_bytes_used{memory_type=\"heap\", cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", host=~\"$node\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by (cluster)\n        (mcac_jvm_memory_used{memory_type=\"heap\", cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "avg"
    },
    {
     "expr": "min by ( cluster)\n        (mcac_jvm_memory_max{memory_type=\"heap\", cluster=\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$node\"})",
     "legendFormat": "Heap memory available"
    }
   ]
  }
 ]
}