{
 "title": "Cassandra Cluster Condensed",
 "description": "Single pane of glass for most important Cassandra metrics",
 "tags": [ "os" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "Prometheus" },
   { "name": "by", "label": "Group By", "query": "cluster,dc,rack,instance" },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{}, cluster)"
    }
   },
   {
    "name": "dc",
    "label": "DataCenter",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\"}, datacenter)"
    }
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\"}, rack)"
    }
   },
   {
    "name": "keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_table_read_total_latency{cluster=~\"$cluster\", datacenter=~\"$dc\"}, keyspace)"
    }
   },
   {
    "name": "table",
    "label": "Table",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_table_read_total_latency{cluster=~\"$cluster\", datacenter=~\"$dc\", keyspace=~\"$keyspace\"}, table)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\"}, pod_name)"
    }
   },
   {
    "name": "latency",
    "label": "Percentile",
    "query": "0.999,0.99,0.98,0.95,0.90,0.75,0.50"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nodes Up",
   "type": "stat",
   "description": "Nodes that are currently running in this time window",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by(pod_name) (org_apache_cassandra_metrics_thread_pools_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"} >= 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "Nodes Down",
   "type": "stat",
   "description": "Nodes that are currently not running in this time window",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(absent(sum(rate(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[1m:30s])))) OR vector(0)"
    }
   ]
  },
  {
   "title": "CQL Clients",
   "type": "stat",
   "description": "Number of connected clients during this time window",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_client_connected_native_clients{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "CQL Requests / $rate",
   "type": "stat",
   "description": "Rate of CQL requests during this window",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Dropped Messages / $rate",
   "type": "stat",
   "description": "Rate of Dropped requests during this window",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_dropped_mutations{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Tombstone reads / $rate",
   "type": "stat",
   "description": "Tombstone reads over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_tombstone_scanned_histogram_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Timeouts / $rate",
   "type": "stat",
   "description": "Client timeouts over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_client_request_timeouts_total{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Hints / $rate",
   "type": "stat",
   "description": "Hints stored over the last $rate",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_storage_total_hints{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Compactions / $rate",
   "type": "stat",
   "description": "Rate of compactions during this window",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Pending Compactions / $rate",
   "type": "stat",
   "description": "Rate of compactions during this window",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Data Size",
   "type": "stat",
   "description": "Data",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_table_live_disk_space_used{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"})"
    }
   ]
  },
  {
   "title": "GC Time / $rate",
   "type": "stat",
   "description": "Data",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_g1_old_generation_time{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) + sum(rate(jvm_gc_g1_young_generation_time{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate]))"
    }
   ]
  },
  {
   "title": "Condensed Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests Served / $by / $rate",
   "type": "timeseries",
   "description": "(no keyspace/table filters apply)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_client_request_latency_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by ($by, request_type)",
     "legendFormat": "$by:{{$by}} {{request_type}}"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_client_connected_native_clients{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}) by ($by)",
     "legendFormat": "$by:{{$by}}:Clients Connected"
    }
   ]
  },
  {
   "title": "Coordinator $latency Latency / $by",
   "type": "timeseries",
   "description": "(no keyspace/table filters apply)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($latency, sum(rate(org_apache_cassandra_metrics_client_request_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by (le, request_type, $by))",
     "legendFormat": "$by:{{$by}} {{$latency}} {{request_type}}"
    }
   ]
  },
  {
   "title": "Memtable Space $keyspace.$table / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(org_apache_cassandra_metrics_table_memtable_off_heap_size{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : Off Heap"
    },
    {
     "expr": "sum(org_apache_cassandra_metrics_table_memtable_on_heap_size{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}) by ($by)",
     "legendFormat": "{{$by}} : On Heap"
    },
    {
     "expr": "sum(idelta(org_apache_cassandra_metrics_table_memtable_switch_count{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Flushes"
    },
    {
     "expr": "sum(idelta(org_apache_cassandra_metrics_table_pending_flushes{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}} : Pending Flushes"
    }
   ]
  },
  {
   "title": "Compactions $keyspace.$table / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_compaction_bytes_written{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Bytes Compacted"
    },
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_table_pending_compactions{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Pending Compactions"
    },
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_compaction_completed_tasks{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{by}} : Completed Compactions"
    }
   ]
  },
  {
   "title": "Table $latency Latency / $by",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_range_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Range Scan"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_read_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Read"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_write_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Local Write"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_coordinator_read_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Read"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_coordinator_scan_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Range Scan"
    },
    {
     "expr": "histogram_quantile($latency, sum(irate(org_apache_cassandra_metrics_table_coordinator_write_latency_bucket{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", keyspace=~\"$keyspace\", table=~\"$table\", pod_name=~\"$host\"}[$rate])) by (le, $by))",
     "legendFormat": "$by:{{$by}} Coordinator Write"
    }
   ]
  },
  {
   "title": "Streaming / $by / $rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_streaming_total_incoming_bytes{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}: Incoming Stream"
    },
    {
     "expr": "sum(irate(org_apache_cassandra_metrics_streaming_total_outgoing_bytes{cluster=~\"$cluster\", datacenter=~\"$dc\", rack=~\"$rack\", pod_name=~\"$host\"}[$rate])) by ($by)",
     "legendFormat": "{{$by}}: Outgoing Stream"
    }
   ]
  }
 ]
}